name: autoupdate
on:
  push:
    branches:
      - 'main'

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: autoupdate
        uses: ./
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PR_FILTER: "labelled"
          PR_LABELS: "sync"
